# Generated by Django 3.0.6 on 2020-06-05 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charlie', '0003_auto_20200603_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
